/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatSessionItem: typeof import('./src/components/chat/ChatSessionItem.vue')['default']
    ChatTopBar: typeof import('./src/components/chat/ChatTopBar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EnhancedChatInput: typeof import('./src/components/chat/EnhancedChatInput.vue')['default']
    EnhancedMessageBubble: typeof import('./src/components/chat/EnhancedMessageBubble.vue')['default']
    ErrorBoundary: typeof import('./src/components/common/ErrorBoundary.vue')['default']
    FilePreviewDialog: typeof import('./src/components/common/FilePreviewDialog.vue')['default']
    MessageActions: typeof import('./src/components/message-bubble/MessageActions.vue')['default']
    MessageAttachments: typeof import('./src/components/message-bubble/MessageAttachments.vue')['default']
    MessageBubble: typeof import('./src/components/message-bubble/index.vue')['default']
    MessageContent: typeof import('./src/components/message-bubble/MessageContent.vue')['default']
    MessageHeader: typeof import('./src/components/message-bubble/MessageHeader.vue')['default']
    MessageThinking: typeof import('./src/components/message-bubble/MessageThinking.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonLoader: typeof import('./src/components/common/SkeletonLoader.vue')['default']
    ThinkingPanel: typeof import('./src/components/chat/ThinkingPanel.vue')['default']
    VirtualMessageList: typeof import('./src/components/common/VirtualMessageList.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
